image: tetraweb/php
services:
    - mysql
before_script:
  - composer install
  - composer install --dev --prefer-dist --no-interaction --quiet

stages:
  - test

test:
  script:
  - php vendor/phpunit/phpunit/phpunit
